name: Puppet Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  puppet-lint:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: puppet-lint
      uses: scottbrenner/puppet-lint-action@v1.0.4
      with:
        args: ./
